version: '3.9'
services:
  traefik:
    image: traefik:v3.0
    profiles:
    - disabled  # Disabled in production: use Setup-Macspark Traefik on 'proxy' network
    env_file: .env
    command:
    - --api.dashboard=true
    - --api.insecure=false
    - --providers.docker=true
    - --providers.docker.exposedbydefault=false
    - --entrypoints.web.address=:80
    - --entrypoints.websecure.address=:443
    - --entrypoints.web.http.redirections.entrypoint.to=websecure
    - --entrypoints.web.http.redirections.entrypoint.scheme=https
    - --entrypoints.web.http.redirections.entrypoint.permanent=true
    - --certificatesresolvers.letsencrypt.acme.tlschallenge=true
    - --certificatesresolvers.letsencrypt.acme.email=admin@yourdomain.com
    - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
    - --log.level=INFO
    - --accesslog=true
    - --metrics.prometheus=true
    - --metrics.prometheus.addEntryPointsLabels=true
    - --metrics.prometheus.addServicesLabels=true
    ports:
    - 80:80
    - 443:443
    - 8080:8080
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - ./ops/traefik/letsencrypt:/letsencrypt
    - ./ops/traefik/traefik.yml:/etc/traefik/traefik.yml:ro
    - ./ops/traefik/dynamic:/etc/traefik/dynamic:ro
    networks:
    - sparkone-network
    - reverse-proxy
    labels:
    - traefik.enable=true
    - traefik.http.routers.traefik.rule=Host(`traefik.yourdomain.com`)
    - traefik.http.routers.traefik.entrypoints=websecure
    - traefik.http.routers.traefik.tls.certresolver=letsencrypt
    - traefik.http.routers.traefik.service=api@internal
    - traefik.http.routers.traefik.middlewares=auth
    - traefik.http.middlewares.auth.basicauth.users=${TRAEFIK_BASICAUTH_USERS}
  api:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 2
    env_file: .env
    environment:
    - TZ=${TZ:-America/Sao_Paulo}
    - PYTHONPATH=src
    - ALLOW_PARTIAL_STARTUP=false
    volumes:
    - ./uploads:/app/uploads
    - ./secrets:/secrets:ro
    depends_on:
    - redis
    networks:
    - sparkone-network
    - proxy
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.middlewares.rate-limit.ratelimit.average=50
      - traefik.http.middlewares.rate-limit.ratelimit.burst=100
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true
      - traefik.http.middlewares.security-headers.headers.customrequestheaders.X-Forwarded-For=
      - traefik.http.middlewares.security-headers.headers.customrequestheaders.X-Forwarded-Proto=https
      - traefik.http.routers.sparkone-api.entrypoints=web
      - traefik.http.routers.sparkone-api.middlewares=security-headers,rate-limit,redirect-to-https
      - traefik.http.routers.sparkone-api.rule=Host(`sparkone-ai.macspark.dev`)
      - traefik.http.services.sparkone-api.loadbalancer.server.port=8000
      - traefik.http.routers.sparkone-api-secure.entrypoints=websecure
      - traefik.http.routers.sparkone-api-secure.rule=Host(`sparkone-ai.macspark.dev`)
      - traefik.http.routers.sparkone-api-secure.tls=true
      - traefik.http.routers.sparkone-api-secure.tls.certresolver=letsencrypt
      - traefik.http.routers.sparkone-api-secure.service=sparkone-api
    restart: unless-stopped
    healthcheck:
      test:
      - CMD-SHELL
      - python -c "import urllib.request,sys; sys.exit(0 if urllib.request.urlopen('http://localhost:8000/health/').status==200 else 1)"
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
  worker:
    build: .
    command: python -m app.workers.scheduler
    env_file: .env
    environment:
    - TZ=${TZ:-America/Sao_Paulo}
    volumes:
    - ./uploads:/app/uploads
    - ./secrets:/secrets:ro
    depends_on:
    - redis
    networks:
    - sparkone-network
    restart: unless-stopped
  db:
    image: ankane/pgvector:v0.5.1  # PostgreSQL 16 with pgvector extension
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-sparkone}
      - POSTGRES_USER=${POSTGRES_USER:-sparkone}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-sparkone}
    networks:
      - sparkone-network
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U ${POSTGRES_USER:-sparkone} -d ${POSTGRES_DB:-sparkone}
      interval: 30s
      timeout: 10s
      retries: 5
  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    networks:
      sparkone-network:
        aliases:
          - cache
    restart: unless-stopped
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      interval: 30s
      timeout: 10s
      retries: 3
  prometheus:
    image: prom/prometheus:v2.54.1
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    - --storage.tsdb.path=/prometheus
    - --web.console.libraries=/etc/prometheus/console_libraries
    - --web.console.templates=/etc/prometheus/consoles
    - --storage.tsdb.retention.time=30d
    - --web.enable-lifecycle
    - --web.enable-admin-api
    volumes:
    - ./ops/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    - ./ops/prometheus/alerts.yml:/etc/prometheus/alerts.yml:ro
    - prometheus_data:/prometheus
    networks:
    - sparkone-network
    labels:
    - traefik.enable=true
    - traefik.http.routers.prometheus.rule=Host(`prometheus.yourdomain.com`)
    - traefik.http.routers.prometheus.entrypoints=websecure
    - traefik.http.routers.prometheus.tls.certresolver=letsencrypt
    - traefik.http.routers.prometheus.service=prometheus
    - traefik.http.services.prometheus.loadbalancer.server.port=9090
    - traefik.http.routers.prometheus.middlewares=auth
    restart: unless-stopped
  grafana:
    image: grafana/grafana:11.2.0
    environment:
    - GF_SECURITY_ADMIN_PASSWORD=admin123
    - GF_USERS_ALLOW_SIGN_UP=false
    - GF_SERVER_ROOT_URL=https://grafana.yourdomain.com
    - GF_INSTALL_PLUGINS=grafana-piechart-panel
    volumes:
    - grafana_data:/var/lib/grafana
    - ./ops/grafana/dashboard-overview.json:/etc/grafana/provisioning/dashboards/dashboard-overview.json:ro
    networks:
    - sparkone-network
    labels:
    - traefik.enable=true
    - traefik.http.routers.grafana.rule=Host(`grafana.yourdomain.com`)
    - traefik.http.routers.grafana.entrypoints=websecure
    - traefik.http.routers.grafana.tls.certresolver=letsencrypt
    - traefik.http.routers.grafana.service=grafana
    - traefik.http.services.grafana.loadbalancer.server.port=3000
    restart: unless-stopped
  alertmanager:
    image: prom/alertmanager:v0.27.0
    command:
    - --config.file=/etc/alertmanager/alertmanager.yml
    - --storage.path=/alertmanager
    - --web.external-url=https://alertmanager.yourdomain.com
    volumes:
    - ./ops/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
    - alertmanager_data:/alertmanager
    networks:
    - sparkone-network
    labels:
    - traefik.enable=true
    - traefik.http.routers.alertmanager.rule=Host(`alertmanager.yourdomain.com`)
    - traefik.http.routers.alertmanager.entrypoints=websecure
    - traefik.http.routers.alertmanager.tls.certresolver=letsencrypt
    - traefik.http.routers.alertmanager.service=alertmanager
    - traefik.http.services.alertmanager.loadbalancer.server.port=9093
    - traefik.http.routers.alertmanager.middlewares=auth
    restart: unless-stopped
  jaeger:
    image: jaegertracing/all-in-one:1.58
    environment:
    - COLLECTOR_OTLP_ENABLED=true
    - SPAN_STORAGE_TYPE=memory
    networks:
    - sparkone-network
    labels:
    - traefik.enable=true
    - traefik.http.routers.jaeger.rule=Host(`jaeger.yourdomain.com`)
    - traefik.http.routers.jaeger.entrypoints=websecure
    - traefik.http.routers.jaeger.tls.certresolver=letsencrypt
    - traefik.http.routers.jaeger.service=jaeger
    - traefik.http.services.jaeger.loadbalancer.server.port=16686
    - traefik.http.routers.jaeger.middlewares=auth
    restart: unless-stopped
volumes:
  pgdata: null
  redis_data: null
  prometheus_data: null
  grafana_data: null
  alertmanager_data: null
networks:
  sparkone-network:
    driver: bridge
  proxy:
    external: true
    name: proxy
