global:
  scrape_interval: 15s
  evaluation_interval: 30s

rule_files:
  - /etc/prometheus/alerts.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

scrape_configs:
  - job_name: "sparkone-api"
    metrics_path: /metrics
    static_configs:
      - targets: ["api:8000"]
  - job_name: "traefik"
    metrics_path: /metrics
    static_configs:
      - targets: ["traefik:8082"]
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
