version: "3.9"

services:
  api:
    build: .
    command: uvicorn src.app.main:app --host 0.0.0.0 --port 8000 --reload
    env_file: ../.env.development
    environment:
      - TZ=${TZ:-America/Sao_Paulo}
    volumes:
      - .:/app
      - ../secrets:/secrets:ro
    ports:
      - "8000:8000"
    depends_on:
      - db
      - cache

  worker:
    build: .
    command: python -m src.app.workers.scheduler
    env_file: ../.env.development
    environment:
      - TZ=${TZ:-America/Sao_Paulo}
    volumes:
      - .:/app
      - ../secrets:/secrets:ro
    depends_on:
      - db
      - cache

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-sparkone}
      - POSTGRES_USER=${POSTGRES_USER:-sparkone}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-sparkone}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: >
      postgres -c shared_preload_libraries=pg_stat_statements
               -c max_connections=200
               -c shared_buffers=256MB

  cache:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  ngrok:
    image: ngrok/ngrok:latest
    command: http api:8000
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    depends_on:
      - api

volumes:
  pgdata:
