groups:
  - name: sparkone-alerts
    rules:
      # Alertas de Sincronização
      - alert: NotionSyncFailures
        expr: increase(sparkone_notion_sync_total{status="failure"}[15m]) >= 1
        for: 0m
        labels:
          severity: warning
          service: notion
        annotations:
          summary: "Falha em sincronizações com Notion"
          description: "Detectado ao menos 1 erro no Notion nos últimos 15 minutos"

      - alert: SheetsSyncFailures
        expr: increase(sparkone_sheets_sync_total{status="failure"}[15m]) >= 1
        for: 0m
        labels:
          severity: critical
          service: sheets
        annotations:
          summary: "Falha em sincronizações com Google Sheets"
          description: "Detectado ao menos 1 erro no Google Sheets nos últimos 15 minutos"

      # Alertas de Performance
      - alert: HighRequestRate
        expr: rate(sparkone_http_requests_total[1m]) > 100
        for: 1m
        labels:
          severity: warning
          service: api
        annotations:
          summary: "Taxa de requisições elevada"
          description: "API recebendo mais de 100 requests/min nos últimos 1 minuto"

      - alert: HighLatency
        expr: histogram_quantile(0.95, rate(sparkone_http_request_latency_seconds_bucket[5m])) > 2.0
        for: 2m
        labels:
          severity: warning
          service: api
        annotations:
          summary: "Latência elevada na API"
          description: "95% das requisições estão levando mais de 2 segundos para responder"

      - alert: DatabaseSlowQueries
        expr: avg(sparkone_database_query_duration_seconds) > 0.5
        for: 3m
        labels:
          severity: warning
          service: database
        annotations:
          summary: "Queries lentas no banco de dados"
          description: "Tempo médio de query no banco está acima de 500ms por 3 minutos"

      - alert: WhatsAppNotificationFailures
        expr: increase(sparkone_whatsapp_notifications_total{status="failure"}[1h]) >= 5
        for: 0m
        labels:
          severity: warning
          service: whatsapp
        annotations:
          summary: "Falhas em notificações WhatsApp"
          description: "5 ou mais falhas de notificação WhatsApp na última hora"
