version: '3.8'

services:
  evolution-api:
    image: evolutionapi/evolution-api:latest
    container_name: sparkone-evolution-api
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - AUTHENTICATION_API_KEY=sparkone_2024_secure_key
      - WEBHOOK_GLOBAL_URL=https://your-n8n-domain.com/webhook/
      - WEBHOOK_GLOBAL_ENABLED=true
      - WEBHOOK_GLOBAL_WEBHOOK_BY_EVENTS=true
      - WEBHOOK_GLOBAL_WEBHOOK_BY_EVENTS_ENABLED=APPLICATION_STARTUP,QRCODE_UPDATED,MESSAGES_UPSERT
      - DATABASE_CONNECTION_URI=file:./database.sqlite
      - LOG_LEVEL=ERROR
      - LOG_COLOR=false
      - LOG_BAILEYS=error
    volumes:
      - evolution-data:/evolution/instances
      - evolution-logs:/evolution/logs
    networks:
      - sparkone-network

  n8n:
    image: n8nio/n8n:latest
    container_name: sparkone-n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=sparkone2024
      - WEBHOOK_URL=https://your-n8n-domain.com/
      - GENERIC_TIMEZONE=America/Sao_Paulo
      - N8N_LOG_LEVEL=info
      - N8N_METRICS=true
    volumes:
      - n8n-data:/home/node/.n8n
    networks:
      - sparkone-network
    depends_on:
      - evolution-api

volumes:
  evolution-data:
  evolution-logs:
  n8n-data:

networks:
  sparkone-network:
    driver: bridge

