route:
  receiver: "default"
  group_by: ["alertname", "service"]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  routes:
    - matchers:
        - severity = "critical"
      receiver: "critical"
      repeat_interval: 1h

receivers:
  - name: "default"
    email_configs:
      - to: "admin@yourdomain.com"
        from: "alerts@yourdomain.com"
        smarthost: "smtp.gmail.com:587"
        auth_username: "your_email@gmail.com"
        auth_password: "your_app_password"
        headers:
          Subject: "SparkOne Alert: {{ .CommonAnnotations.summary }}"
        html: |
          <h2>Alerta SparkOne</h2>
          <p><strong>Descrição:</strong> {{ .CommonAnnotations.description }}</p>
          <p><strong>Severidade:</strong> {{ .CommonLabels.severity }}</p>
          <p><strong>Serviço:</strong> {{ .CommonLabels.service }}</p>
          <ul>
          {{- range .Alerts }}
          <li><strong>Início:</strong> {{ .StartsAt }} — <strong>Labels:</strong> {{ .Labels }}</li>
          {{- end }}
          </ul>
  - name: "critical"
    email_configs:
      - to: "admin@yourdomain.com"
        from: "critical-alerts@yourdomain.com"
        smarthost: "smtp.gmail.com:587"
        auth_username: "your_email@gmail.com"
        auth_password: "your_app_password"
        headers:
          Subject: "CRÍTICO SparkOne: {{ .CommonAnnotations.summary }}"
        html: |
          <h2 style="color: red;">ALERTA CRÍTICO - SparkOne</h2>
          <p><strong>Descrição:</strong> {{ .CommonAnnotations.description }}</p>
          <p><strong>Severidade:</strong> {{ .CommonLabels.severity }}</p>
          <p><strong>Serviço:</strong> {{ .CommonLabels.service }}</p>
          <ul>
          {{ range .Alerts }}
          <li><strong>{{ .Labels.instance }}</strong> — {{ .Annotations.description }}</li>
          {{ end }}
          </ul>

inhibit_rules:
  - source_matchers:
      - severity = "critical"
    target_matchers:
      - severity = "warning"
    equal: ["alertname", "service"]
