name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('pyproject.toml') }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .[dev]

      - name: Lint (ruff)
        run: python -m ruff check src tests

      - name: Format check (black)
        run: python -m black --check src tests

      - name: Type check (mypy)
        run: python -m mypy src

      - name: Unit tests (pytest)
        env:
          PYTHONPATH: src
        run: python -m pytest --cov=src --cov-report=xml

      - name: Upload coverage to Codecov (optional)
        if: ${{ secrets.CODECOV_TOKEN != '' }}
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Dependency scan (pip-audit)
        run: |
          python -m pip install pip-audit
          pip-audit -r pyproject.toml
